### PR TITLE
Stream pages

### PR DESCRIPTION
**Pull request by ashwinbhaskar**

### CODE REVIEW

**Review by siftrics — CHANGES_REQUESTED** [review]
Please

1. Rebase this branch onto master to fix the conflicts with it.
2. Replace the contents of README.md with this: [https://gist.githubusercontent.com/siftrics/c7809bd312e79d7aec39008a7560238a/raw/d0e2fa4a23ba0f22c71fa4e704e623c150b94400/README.md](https://gist.githubusercontent.com/siftrics/c7809bd312e79d7aec39008a7560238a/raw/d0e2fa4a23ba0f22c71fa4e704e623c150b94400/README.md).

Then we can probably merge this.

**Comment by ashwinbhaskar** [comment]
@siftrics changes done

**Comment by ashwinbhaskar** [comment]
@siftrics also when you merge you can maybe squash the commits into a single commit `Fixes #5 Stream pages as they are fetched`. This way we can maintain only feature commits on master

**Comment by siftrics** [comment]
@ashwinbhaskar Sorry for the late response. This all looks good, but there are still conflicts that must be resolved before I can merge this in. You can resolve the conflicts by running this command:

```
$ git checkout stream_pages
$ git rebase master
Auto-merging src/sight/core.clj
CONFLICT (content): Merge conflict in src/sight/core.clj
error: could not apply 0454f22... Improve readability, use clojure idioms, format code
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 0454f22... Improve readability, use clojure idioms, format code
```

At this point, you should be able to see that core.clj has conflicts:

```
$ git status -sb
## HEAD (no branch)
UU src/sight/core.clj
```

After opening core.clj and resolving the conflicts, you can complete the rebase with these commands:

```
$ git add core.clj
$ git rebase --continue
```

Finally, push the changes (forcefully, since you rebased) with

```
$ git push -f origin stream_pages
```

Once the conflicts are resolved, I can click the merge button and we should be good to go.

**Comment by ashwinbhaskar** [comment]
@siftrics I have merged it. Can you see if you are able to merge now?

**Pull request merged**
